name: project_git_santosh
description: ''
version: v0.6
author: santosh@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projectgitsantosh
  parentArtefactID: santoshcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-05 08:57:30'
pipelines:
  pipelines/pl_useGem02:
    name: pl_useGem02
    description: Using Gem02
    author: santosh@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-20 17:28:07'
    datasets:
      inputs:
      - datasets/ds_src_input
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/ds_src_input:
    name: ds_src_input
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-03-20 17:37:48'
    mode: batch
    physicalDatasets:
      fabric_santosh:
        fabricId: 9997
        datasetType: File
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-03-20 17:37:48'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/CustomLimit:
      name: CustomLimit
      category: Transform
      subCategory: ''
      description: null
      author: santosh@cloudaeon.net
      mode: batch
      files:
      - santoshcloudaeonnetteam_projectgitsantosh/gems/CustomLimit.py
      gemType: ComponentGem
      dependencies: []
      createdAt: '2024-03-07 15:35:07'
    gems/CustomIntCols:
      name: CustomIntCols
      category: Custom
      subCategory: ''
      description: null
      author: santosh@cloudaeon.net
      mode: batch
      files:
      - santoshcloudaeonnetteam_projectgitsantosh/gems/CustomIntCols.py
      gemType: ComponentGem
      dependencies: []
      createdAt: '2024-03-20 17:54:27'
    gems/CustomSynthData:
      name: CustomSynthData
      category: Custom
      subCategory: ''
      description: null
      author: santosh@cloudaeon.net
      mode: batch
      files:
      - santoshcloudaeonnetteam_projectgitsantosh/gems/CustomSynthData.py
      gemType: ComponentGem
      dependencies:
      - type: pypi
        modifiedAt: '2024-03-23T11:59:51.601Z'
        package: faker==24.3.0
        name: Faker
        description: ''
        enabled: true
        id: EZwiQSfWCckpQCUVc6jgj
        createdAt: '2024-03-23T11:59:51.601Z'
        entity: Gem
        addToPipeline: true
        editable: true
      createdAt: '2024-03-21 04:12:47'
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-05 08:57:30'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- description: ''
  id: XQSIj9OwUrLdvRiJ-uAMV
  editable: true
  enabled: true
  type: pypi
  name: Faker
  scope: Project
  package: faker==24.3.0
  entity: Project
  modifiedAt: '2024-03-23T11:53:55.718Z'
  createdAt: '2024-03-23T11:53:55.718Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.4
    isDefault: true
    author: null
    createdAt: '2024-03-05 08:56:17'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-05 08:56:17'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
